async function updateCode() {
    await fetch("https://api.github.com/repos/marktheshark1234/LANSchoolProject/actions/workflows/update-code.yml/dispatches", {
        method: "POST",
        headers: {
            "Accept": "application/vnd.github.v3+json",
            "Authorization": "Bearer YOUR_GITHUB_PERSONAL_ACCESS_TOKEN"
        },
        body: JSON.stringify({ "ref": "main" })
    });

    alert("New code has been generated!");
}
